import React from "react";
import "./profile.css";
import { Card, CardMedia } from "@mui/material";

const Profile = () => {
  return (
    <div>
      {/*<head>
    <meta charset="utf-8" />
    <link
      rel="preload"
      as="font"
      href="../../_next/static/media/2c5243ddb420350b-s.p.woff2"
      crossorigin=""
      type="font/woff2"
    />
    <link
      rel="preload"
      as="font"
      href="../../_next/static/media/41d071df82ce7b14-s.p.woff"
      crossorigin=""
      type="font/woff"
    />
    <link
      rel="preload"
      as="font"
      href="../../_next/static/media/54867ac977eda96b-s.p.woff2"
      crossorigin=""
      type="font/woff2"
    />
    <link
      rel="preload"
      as="font"
      href="../../_next/static/media/664ad6406ba55027-s.p.woff"
      crossorigin=""
      type="font/woff"
    />
    <link
      rel="preload"
      as="font"
      href="../../_next/static/media/bdcb71c25532c7a7-s.p.woff2"
      crossorigin=""
      type="font/woff2"
    />
    <link
      rel="stylesheet"
      href="../../_next/static/css/d6198bcf2c342a81.css"
      data-precedence="next"
    />
    <title>Jobi - Job Portal &amp; Job Board React NextJS Template</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="../../favicon.ico" type="image/x-icon" sizes="any" />
    <meta name="next-size-adjust" />
    <link rel="icon" href="../../favicon.ico" sizes="any" />
    <script
      src="../../_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
      nomodule=""
    ></script>
  </head>*/}
      <div className="__variable_e76efa __variable_95782f">
        <div className="main-page-wrapper">
          <div className="dashboard-body">
            <div className="position-relative">
              <header className="dashboard-header">
                <div className="d-flex align-items-center justify-content-end">
                  <button className="dash-mobile-nav-toggler d-block d-md-none me-auto">
                    <span></span>
                  </button>
                  <form className="search-form" action="#">
                    <input type="text" placeholder="Search here.." />
                    <button>
                      <img
                        alt="search"
                        loading="lazy"
                        width="16"
                        height="17"
                        decoding="async"
                        data-nimg="1"
                        className="lazy-img m-auto"
                        style={{ color: "transparent" }}
                        src="https://jobi-nextjs.vercel.app/_next/static/media/icon_10.35c41a63.svg"
                      />
                    </button>
                  </form>
                  <div className="profile-notification ms-2 ms-md-5 me-4">
                    <button
                      className="noti-btn dropdown-toggle"
                      type="button"
                      id="notification-dropdown"
                      data-bs-toggle="dropdown"
                      data-bs-auto-close="outside"
                      aria-expanded="false"
                    >
                      <img
                        alt="Notification"
                        loading="lazy"
                        width="21"
                        height="24"
                        decoding="async"
                        data-nimg="1"
                        className="lazy-img"
                        style={{ color: "transparent" }}
                        src="https://jobi-nextjs.vercel.app/_next/static/media/icon_11.32f89e94.svg"
                      />
                      <div className="badge-pill"></div>
                    </button>
                    <ul
                      className="dropdown-menu"
                      aria-labelledby="notification-dropdown"
                    >
                      <li>
                        <h4>Notification</h4>
                        <ul className="style-none notify-list">
                          <li className="d-flex align-items-center unread">
                            <img
                              alt="icon"
                              loading="lazy"
                              width="36"
                              height="36"
                              decoding="async"
                              data-nimg="1"
                              className="lazy-img icon"
                              style={{ color: "transparent" }}
                              src="https://jobi-nextjs.vercel.app/_next/static/media/icon_36.d044b698.svg"
                            />
                            <div className="flex-fill ps-2">
                              <h6>You have 3 new mails</h6>
                              <span className="time">3 hours ago</span>
                            </div>
                          </li>
                          <li className="d-flex align-items-center">
                            <img
                              alt="icon"
                              loading="lazy"
                              width="36"
                              height="36"
                              decoding="async"
                              data-nimg="1"
                              className="lazy-img icon"
                              style={{ color: "transparent" }}
                              src="https://jobi-nextjs.vercel.app/_next/static/media/icon_37.34c12156.svg"
                            />
                            <div className="flex-fill ps-2">
                              <h6>You have 5 new mails</h6>
                              <span className="time">6 hours ago</span>
                            </div>
                          </li>
                          <li className="d-flex align-items-center unread">
                            <img
                              alt="icon"
                              loading="lazy"
                              width="36"
                              height="36"
                              decoding="async"
                              data-nimg="1"
                              className="lazy-img icon"
                              style={{ color: "transparent" }}
                              src="https://jobi-nextjs.vercel.app/_next/static/media/icon_38.2db06cc7.svg"
                            />
                            <div className="flex-fill ps-2">
                              <h6>You have 7 new mails</h6>
                              <span className="time">9 hours ago</span>
                            </div>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                  <div>
                    <a
                      className="job-post-btn tran3s"
                      href="../employ-dashboard/submit-job.html"
                    >
                      Post a Job
                    </a>
                  </div>
                </div>
              </header>

              <h2 className="main-title">My Profile</h2>

              <Card style={{ margin: "25px", borderRadius: "25px" }}>
                <div className="bg-white card-box border-20">
                  <div className="user-avatar-setting d-flex align-items-center mb-30">
                    <img
                      alt="avatar"
                      loading="lazy"
                      width="68"
                      height="68"
                      decoding="async"
                      data-nimg="1"
                      className="lazy-img user-img"
                      style={{ color: "transparent" }}
                      src="https://jobi-nextjs.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Favatar_02.9163fcfc.jpg&w=96&q=75"
                    />
                    <div className="upload-btn position-relative tran3s ms-4 me-3">
                      Upload new photo
                      <input
                        type="file"
                        id="uploadImg"
                        placeholder=""
                        name="uploadImg"
                      />
                    </div>
                    <button className="delete-btn tran3s">Delete</button>
                  </div>
                  <div className="dash-input-wrapper mb-30">
                    <label for="">Full Name*</label>
                    <input type="text" placeholder="Md James Brower" />
                  </div>
                  <div className="dash-input-wrapper">
                    <label for="">Bio*</label>
                    <textarea
                      className="size-lg"
                      placeholder="Write something interesting about you...."
                    ></textarea>
                    <div className="alert-text">
                      Brief description for your profile. URLs are hyperlinked.
                    </div>
                  </div>
                </div>
              </Card>

              <Card style={{ margin: "25px", borderRadius: "25px" }}>
                <div className="bg-white card-box border-20 mt-40">
                  <h4 className="dash-title-three">Social Media</h4>
                  <div className="dash-input-wrapper mb-20">
                    <label for="">Network 1</label>
                    <input type="text" placeholder="#" />
                  </div>
                  <div className="dash-input-wrapper mb-20">
                    <label for="">Network 2</label>
                    <input type="text" placeholder="#" />
                  </div>
                  <a href="#" className="dash-btn-one">
                    <i className="bi bi-plus"></i> Add more link
                  </a>
                </div>
              </Card>

              <Card style={{ margin: "25px", borderRadius: "25px" }}>
                <div className="bg-white card-box border-20 mt-40">
                  <h4 className="dash-title-three">Address &amp; Location</h4>
                  <div className="row">
                    <div className="col-12">
                      <div className="dash-input-wrapper mb-25">
                        <label for="">Address*</label>
                        <input
                          type="text"
                          placeholder="Cowrasta, Chandana, Gazipur Sadar"
                        />
                      </div>
                    </div>
                    <div className="col-lg-3">
                      <div className="dash-input-wrapper mb-25">
                        <label for="">Country*</label>
                        <div
                          className="nice-select false"
                          role="button"
                          tabindex="0"
                        >
                          <span className="current">Afghanistan</span>
                          <ul className="list" role="menubar">
                            <li
                              data-value="Afghanistan"
                              className="option selected focus"
                              role="menuitem"
                            >
                              Afghanistan
                            </li>
                            <li
                              data-value="Albania"
                              className="option false"
                              role="menuitem"
                            >
                              Albania
                            </li>
                            <li
                              data-value="Belgium"
                              className="option false"
                              role="menuitem"
                            >
                              Belgium
                            </li>
                            <li
                              data-value="Barbados"
                              className="option false"
                              role="menuitem"
                            >
                              Barbados
                            </li>
                            <li
                              data-value="Australia"
                              className="option false"
                              role="menuitem"
                            >
                              Australia
                            </li>
                            <li
                              data-value="Angola"
                              className="option false"
                              role="menuitem"
                            >
                              Angola
                            </li>
                            <li
                              data-value="Austria"
                              className="option false"
                              role="menuitem"
                            >
                              Austria
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3">
                      <div className="dash-input-wrapper mb-25">
                        <label for="">City*</label>
                        <div
                          className="nice-select false"
                          role="button"
                          tabindex="0"
                        >
                          <span className="current">Sydney</span>
                          <ul className="list" role="menubar">
                            <li
                              data-value="Sydney"
                              className="option selected focus"
                              role="menuitem"
                            >
                              Sydney
                            </li>
                            <li
                              data-value="Tokyo"
                              className="option false"
                              role="menuitem"
                            >
                              Tokyo
                            </li>
                            <li
                              data-value="Delhi"
                              className="option false"
                              role="menuitem"
                            >
                              Delhi
                            </li>
                            <li
                              data-value="Shanghai"
                              className="option false"
                              role="menuitem"
                            >
                              Shanghai
                            </li>
                            <li
                              data-value="Mumbai"
                              className="option false"
                              role="menuitem"
                            >
                              Mumbai
                            </li>
                            <li
                              data-value="Bangalore"
                              className="option false"
                              role="menuitem"
                            >
                              Bangalore
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3">
                      <div className="dash-input-wrapper mb-25">
                        <label for="">Zip Code*</label>
                        <input type="number" placeholder="1708" />
                      </div>
                    </div>
                    <div className="col-lg-3">
                      <div className="dash-input-wrapper mb-25">
                        <label for="">State*</label>
                        <div
                          className="nice-select false"
                          role="button"
                          tabindex="0"
                        >
                          <span className="current">Sydney</span>
                          <ul className="list" role="menubar">
                            <li
                              data-value="Sydney"
                              className="option selected focus"
                              role="menuitem"
                            >
                              Sydney
                            </li>
                            <li
                              data-value="Tokyo"
                              className="option false"
                              role="menuitem"
                            >
                              Tokyo
                            </li>
                            <li
                              data-value="Delhi"
                              className="option false"
                              role="menuitem"
                            >
                              Delhi
                            </li>
                            <li
                              data-value="Shanghai"
                              className="option false"
                              role="menuitem"
                            >
                              Shanghai
                            </li>
                            <li
                              data-value="Mumbai"
                              className="option false"
                              role="menuitem"
                            >
                              Mumbai
                            </li>
                            <li
                              data-value="Bangalore"
                              className="option false"
                              role="menuitem"
                            >
                              Bangalore
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="col-12">
                      <div className="dash-input-wrapper mb-25">
                        <label for="">Map Location*</label>
                        <div className="position-relative">
                          <input
                            type="text"
                            placeholder="XC23+6XC, Moiran, N105"
                          />
                          <button className="location-pin tran3s">
                            <img
                              alt="icon"
                              loading="lazy"
                              width="17"
                              height="17"
                              decoding="async"
                              data-nimg="1"
                              className="lazy-img m-auto"
                              style={{ color: "transparent" }}
                              src="../../_next/static/media/icon_16.7e4bc712.svg"
                            />
                          </button>
                        </div>
                        <div className="map-frame mt-30">
                          <div className="gmap_canvas h-100 w-100">
                            <iframe
                              className="gmap_iframe h-100 w-100"
                              src="https://maps.google.com/maps?width=600&amp;height=400&amp;hl=en&amp;q=bass%20hill%20plaza%20medical%20centre&amp;t=&amp;z=12&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
                            ></iframe>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </Card>

              <div className="button-group d-inline-flex align-items-center mt-30">
                <a href="#" className="dash-btn-two tran3s me-3">
                  Save
                </a>
                <a href="#" className="dash-cancel-btn tran3s">
                  Cancel
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="Toastify"></div>
        <button className="scroll-top">
          <i className="bi bi-arrow-up-short"></i>
        </button>
      </div>
    </div>
  );
};

export default Profile;
